# Generated by Django 3.2.20 on 2023-08-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230810_1147'),
    ]

    
    def teacher_and_student(apps, schema_editor):
        Teacher = apps.get_model('school', 'Teacher')
        Student = apps.get_model('school', 'Student')

        for student in Student.objects.all():
            teacher = Teacher.objects.get(id=student.teacher_id)
            student.teachers.add(teacher)
    operations = [

        migrations.RunPython(teacher_and_student,)

    ]
