# Generated by Django 3.2.20 on 2023-08-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
